version: '3.3'
services:
    dockeremu:
        build: .
        container_name: dockerEmu
        working_dir: /github/workspace
        environment:
            - PATH=/bin:/usr/bin/
            - CHECKER=/github/workspace/checker
        volumes:
            - '/home/runner/work/SS_Team4_project/SS_Team4_project:/github/workspace'
            - '/home/runner/work/SS_Team4_project/SS_Team4_project/.github/actions/container/UniteTest/:/github/workspace/checker'
        entrypoint:
            - 'bash'
            - 'checker/UniteTest.sh'
