name: c/c++ CD

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: ls
      run: |
        ls -al
    - name: pwd
      run: |
        pwd
    - name: make
      run: |
        make
    - name: run_server_up
      run: |
        ./webserver_fork 8080 &
    - name: run_zap
      run: |
        docker pull owasp/zap2docker-weekly
    - name: filter
      run: |
        ./docker.sh
    - name: cat
      run: |    
        cat testreport.html
              #docker-compose -f .github/actions/container/DAST/docker-compose_1.yml up --build --exit-code-from zap
